#!/usr/bin/env node
/**
 * Expose local OSS Docker ports as HTTPS via cloudflared (Docker CLI).
 * Writes scripts/docker-oss.tunnel.env for Vercel / Hub sync.
 *
 * Usage:
 *   node scripts/oss-tunnel.mjs start
 *   node scripts/oss-tunnel.mjs status
 *   node scripts/oss-tunnel.mjs stop
 */
import { execSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TUNNEL_ENV = path.join(ROOT, "scripts", "docker-oss.tunnel.env");
const CLOUDFLARED_IMAGE = "cloudflare/cloudflared:latest";
const HOST = "host.docker.internal";

/** @type {{ id: string; port: number; env: string; optional?: boolean }[]} */
const SERVICES = [
  { id: "dify", port: 3001, env: "NEXT_PUBLIC_DIFY_URL" },
  { id: "rocketchat", port: 3002, env: "NEXT_PUBLIC_ROCKETCHAT_URL" },
  { id: "outline", port: 3003, env: "NEXT_PUBLIC_OUTLINE_URL" },
  { id: "chatwoot", port: 3004, env: "NEXT_PUBLIC_CHATWOOT_URL" },
  { id: "calcom", port: 3005, env: "NEXT_PUBLIC_CALCOM_URL" },
  { id: "roundcube", port: 8080, env: "NEXT_PUBLIC_ROUNDCUBE_URL" },
  { id: "nextcloud", port: 8081, env: "NEXT_PUBLIC_NEXTCLOUD_URL" },
  { id: "akaunting", port: 8082, env: "NEXT_PUBLIC_AKAUNTING_URL", optional: true },
  { id: "mediacms", port: 8800, env: "NEXT_PUBLIC_MEDIACMS_URL" },
  { id: "livekit", port: 7880, env: "NEXT_PUBLIC_LIVEKIT_URL" },
];

const TUNNEL_URL_RE = /https:\/\/[a-z0-9-]+\.trycloudflare\.com/gi;

function run(cmd, opts = {}) {
  return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"], ...opts });
}

function docker(args) {
  const r = spawnSync("docker", args, { encoding: "utf8" });
  if (r.status !== 0 && r.stderr) {
    throw new Error(r.stderr.trim() || `docker ${args.join(" ")} failed`);
  }
  return (r.stdout || "") + (r.stderr || "");
}

function containerName(id) {
  return `lonex-tunnel-${id}`;
}

function isPortOpen(port) {
  try {
    const out = run(
      `powershell -NoProfile -Command "(Test-NetConnection -ComputerName localhost -Port ${port} -WarningAction SilentlyContinue).TcpTestSucceeded"`,
      { stdio: "pipe" }
    ).trim();
    return out === "True";
  } catch {
    return false;
  }
}

function pullCloudflared() {
  console.log("Pulling cloudflared image...");
  docker(["pull", CLOUDFLARED_IMAGE]);
}

function removeTunnel(id) {
  const name = containerName(id);
  try {
    docker(["rm", "-f", name]);
  } catch {
    /* ignore */
  }
}

function startTunnel(svc) {
  const name = containerName(svc.id);
  removeTunnel(svc.id);
  console.log(`Starting tunnel ${svc.id} → localhost:${svc.port} (${name})`);
  docker([
    "run",
    "-d",
    "--name",
    name,
    "--add-host",
    `${HOST}:host-gateway`,
    CLOUDFLARED_IMAGE,
    "tunnel",
    "--no-autoupdate",
    "--url",
    `http://${HOST}:${svc.port}`,
  ]);
}

function readTunnelUrl(id, attempts = 30) {
  const name = containerName(id);
  for (let i = 0; i < attempts; i++) {
    try {
      const logs = docker(["logs", name]);
      const matches = [...logs.matchAll(TUNNEL_URL_RE)];
      if (matches.length > 0) {
        return matches[matches.length - 1][0];
      }
    } catch {
      /* container may not be ready */
    }
    execSync("powershell -NoProfile -Command Start-Sleep -Seconds 2", { stdio: "ignore" });
  }
  return null;
}

function writeTunnelEnv(urls) {
  const lines = [
    "# Auto-generated by scripts/oss-tunnel.mjs — do not commit",
    `# Created: ${new Date().toISOString()}`,
    "",
  ];
  for (const [key, val] of Object.entries(urls)) {
    lines.push(`${key}=${val}`);
  }
  fs.writeFileSync(TUNNEL_ENV, lines.join("\n") + "\n");
  console.log(`\nWrote ${TUNNEL_ENV}`);
}

function cmdStart() {
  pullCloudflared();
  const urls = {};
  const skipped = [];

  for (const svc of SERVICES) {
    if (!isPortOpen(svc.port)) {
      const msg = `${svc.id}:${svc.port} not listening`;
      if (svc.optional) {
        console.warn(`Skip (optional): ${msg}`);
        skipped.push(svc.id);
        continue;
      }
      console.error(`OSS not running: ${msg}`);
      console.error("Run: .\\scripts\\docker-oss.ps1 up -Profile all -Wait");
      process.exit(1);
    }
    startTunnel(svc);
  }

  console.log("\nWaiting for tunnel URLs...");
  for (const svc of SERVICES) {
    if (skipped.includes(svc.id)) continue;
    const url = readTunnelUrl(svc.id);
    if (!url) {
      console.error(`Failed to get tunnel URL for ${svc.id}`);
      process.exit(1);
    }
    urls[svc.env] = url;
    console.log(`  ${svc.env}=${url}`);
  }

  if (urls.NEXT_PUBLIC_LIVEKIT_URL) {
    const wss = urls.NEXT_PUBLIC_LIVEKIT_URL.replace(/^https:/, "wss:");
    urls.NEXT_PUBLIC_LIVEKIT_MEET_URL =
      `https://meet.livekit.io/custom?liveKitUrl=${encodeURIComponent(wss)}`;
    console.log(`  NEXT_PUBLIC_LIVEKIT_MEET_URL=${urls.NEXT_PUBLIC_LIVEKIT_MEET_URL}`);
  }

  writeTunnelEnv(urls);
  console.log("\nNext: node scripts/sync-vercel-oss-env.mjs");
  console.log("  or: .\\scripts\\docker-vercel.ps1 -Action sync");
}

function cmdStop() {
  for (const svc of SERVICES) {
    removeTunnel(svc.id);
  }
  console.log("Stopped all lonex-tunnel-* containers");
}

function cmdStatus() {
  console.log("Tunnel containers:");
  try {
    const ps = run('docker ps -a --filter "name=lonex-tunnel-" --format "{{.Names}}\t{{.Status}}"');
    console.log(ps || "(none)");
  } catch {
    console.log("(none)");
  }
  if (fs.existsSync(TUNNEL_ENV)) {
    console.log(`\n${TUNNEL_ENV}:`);
    console.log(fs.readFileSync(TUNNEL_ENV, "utf8"));
  }
}

const action = process.argv[2] || "status";
switch (action) {
  case "start":
    cmdStart();
    break;
  case "stop":
    cmdStop();
    break;
  case "status":
    cmdStatus();
    break;
  default:
    console.error("Usage: node scripts/oss-tunnel.mjs start|stop|status");
    process.exit(1);
}
